'''
  Constants for Image Classification Project
'''


BASE_DATASET_FOLDER = 'C:/imageDownloads/'

CARS_ITEMS = ["Chevy Sonic",
    "Ford Fiesta",
    "Honda Fit",
    "Hyundai Accent",
    "Kia Rio",
    "Mazda 2",
    "Mitsubishi Mirage",
    "Nissan Versa",
    "Toyota Yaris",
    "Chevy Cruze",
    "Ford Focus",
    "Honda Civic",
    "Hyundai Elantra",
    "Kia Forte",
    "Mazda 3",
    "Mitsubishi Lancer",
    "Nissan Sentra",
    "Subaru Impreza",
    "Volkswagen Golf",
    "Volkswagen Jetta",
    "Volkswagen Beetle",
    "Chevy Malibu",
    "Ford Fusion",
    "Honda Accord",
    "Hyundai Sonata",
    "Hyundai Azera",
    "Kia Optima",
    "Mazda 6",
    "Nissan Altima",
    "Subaru Legacy",
    "Toyota Camry",
    "Volkswagen Passat",
    "Chevy Impala",
    "Ford Taurus",
    "Kia Cadenza",
    "Nissan Maxima",
    "Toyota Avalon"]

NOT_CARS_ITEMS = ["food",
    "building",
    "face",
    "mountain",
    "animal",
    "landscape",
    "office",
    "person",
    "window",
    "tree",
    "sign",
    "door",
    "bookshelf",
    "chair",
    "table",
    "keyboard",
    "head",
    "clothes",
    "sports",
    "field",
    "weather",
    "screenshot",
    "phone",
    "room",
    "electronics",
    "companies",
    "actor",
    "actress",
    "math",
    "space",
    "mammal",
    "house",
    "kitchen",
    "store",
    "map",
    "washington dc",
    "ocean"]



